### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by CLG68** [bowen-gao/DrugCLIP#6]
Hi,

Do you have ex of a command line to launch a screen of a library X on a target Y?  What is the format of the library, smiles, 2D sd files, 3D sd files, mol2 files?  The receptor is in pdb?

In your figure 3, you have "pre-encoded library", how do you create a pre-encoded library?

I would like to compare the speed of DrugCLIP to BANANA and Panther/ShaEP.

Thanks for your help,
Christian

**Comment by bowen-gao** [comment]
you can see the "retrieval" section in readme to launch a screen.

pre-encoded means encoding all the mols in the library using the pocket
encoder to embedding representations.

**Comment by bowen-gao** [comment]
sorry, should be using the "molecular encoder"

**Comment by CLG68** [comment]
Thank you very much for your reply, I will try that.

Best
